/**
 * @enum
 */

const MailTypes = {
	/* CV */
	CV_CHANGE_REQUEST: 'CV_CHANGE_REQUEST',
	RECEIVED_CV: 'RECEIVED_CV',
	/* RECORD */
	RECORD_CHANGE_REQUEST: 'RECORD_CHANGE_REQUEST',
	RECEIVED_RECORD: 'RECEIVED_RECORD',
	/* REPORT */
	REPORT_CHANGE_REQUEST: 'REPORT_CHANGE_REQUEST',
	UPDATED_REPORT: 'UPDATED_REPORT',
	/* RESULT */
	INTERN_FAILURE: 'INTERN_FAILURE',
	INTERN_COMPLETION: 'INTERN_COMPLETION',
	/* REQUEST */
	ACCEPTED_REQUEST: 'ACCEPTED_REQUEST',
	DENIED_REQUEST: 'DENIED_REQUEST'
};

export default MailTypes;
